/**
 * The MIT License
 *
 * Copyright (C) 2015 Asterios Raptis
 *
 * Permission is hereby granted, free of charge, to any person obtaining
 * a copy of this software and associated documentation files (the
 * "Software"), to deal in the Software without restriction, including
 * without limitation the rights to use, copy, modify, merge, publish,
 * distribute, sublicense, and/or sell copies of the Software, and to
 * permit persons to whom the Software is furnished to do so, subject to
 * the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE
 * LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
 * OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION
 * WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 */
package io.github.astrapi69.crypt.data.factory;

import java.io.IOException;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

import org.bouncycastle.crypto.threshold.ShamirSecretSplitter;
import org.bouncycastle.crypto.threshold.ShamirSplitSecret;
import org.bouncycastle.crypto.threshold.ShamirSplitSecretShare;
import org.bouncycastle.util.Arrays;

/**
 * The factory class {@link ShamirSecretSharingFactory} holds methods for splitting a secret (e.g. a
 * symmetric key) into {@code n} shares of which any {@code threshold} shares are sufficient to
 * reconstruct the original secret, using Shamir's Secret Sharing scheme over GF(256), backed by
 * Bouncy Castle's {@link ShamirSecretSplitter}.
 * <p>
 * Note that Shamir's scheme has no built-in integrity check: combining fewer than {@code threshold}
 * shares does not fail with an error, it silently yields a wrong secret. Callers that need to
 * detect this should verify the recovered secret independently, e.g. by comparing its hash against
 * a known-good value stored alongside the shares.
 */
public final class ShamirSecretSharingFactory
{

	private ShamirSecretSharingFactory()
	{
	}

	/**
	 * Splits the given secret into {@code totalShares} shares of which any {@code threshold} shares
	 * suffice to reconstruct it.
	 *
	 * @param secret
	 *            the secret to split, e.g. a symmetric key
	 * @param threshold
	 *            the minimum number of shares required to reconstruct the secret (1..255)
	 * @param totalShares
	 *            the total number of shares to generate ({@code threshold}..255), must not exceed
	 *            {@code secret.length}
	 * @param random
	 *            the source of randomness for the share coefficients
	 * @return the list of generated shares, in order from index 1 to {@code totalShares}
	 */
	public static List<Share> split(final byte[] secret, final int threshold, final int totalShares,
		final SecureRandom random)
	{
		Objects.requireNonNull(secret);
		Objects.requireNonNull(random);
		if (secret.length == 0)
		{
			throw new IllegalArgumentException("secret must not be empty");
		}
		if (totalShares > secret.length)
		{
			throw new IllegalArgumentException("totalShares (" + totalShares
				+ ") must not exceed the secret length in bytes (" + secret.length + ")");
		}

		final ShamirSecretSplitter splitter = new ShamirSecretSplitter(
			ShamirSecretSplitter.Algorithm.AES, ShamirSecretSplitter.Mode.Table, secret.length,
			random);
		final ShamirSplitSecret result = (ShamirSplitSecret)splitter.resplit(secret, threshold,
			totalShares);
		final ShamirSplitSecretShare[] bcShares = result.getSecretShares();

		final List<Share> shares = new ArrayList<>(totalShares);
		for (int i = 0; i < totalShares; i++)
		{
			shares.add(new Share(i + 1, encode(bcShares[i])));
		}
		return shares;
	}

	/**
	 * Reconstructs the original secret from the given shares.
	 *
	 * @param shares
	 *            at least {@code threshold} of the shares generated by
	 *            {@link #split(byte[], int, int, SecureRandom)}; supplying fewer than the original
	 *            threshold silently yields a wrong secret rather than failing
	 * @return the reconstructed secret
	 */
	public static byte[] combine(final List<Share> shares)
	{
		Objects.requireNonNull(shares);
		if (shares.isEmpty())
		{
			throw new IllegalArgumentException("shares must not be empty");
		}

		final ShamirSplitSecretShare[] bcShares = new ShamirSplitSecretShare[shares.size()];
		for (int i = 0; i < shares.size(); i++)
		{
			final Share share = shares.get(i);
			bcShares[i] = new ShamirSplitSecretShare(share.getValue(), share.getIndex());
		}

		final ShamirSplitSecret splitSecret = new ShamirSplitSecret(
			ShamirSecretSplitter.Algorithm.AES, ShamirSecretSplitter.Mode.Table, bcShares);
		return decode(splitSecret);
	}

	// package-private instead of private so that the IOException path, which Bouncy Castle's own
	// implementations never take but the SecretShare contract allows, can be exercised in a test
	static byte[] encode(final ShamirSplitSecretShare share)
	{
		try
		{
			return share.getEncoded();
		}
		catch (final IOException ioException)
		{
			throw new IllegalStateException("Failed to encode a Shamir secret share", ioException);
		}
	}

	// package-private instead of private so that the IOException path, which Bouncy Castle's own
	// implementations never take but the SplitSecret contract allows, can be exercised in a test
	static byte[] decode(final ShamirSplitSecret splitSecret)
	{
		try
		{
			return splitSecret.getSecret();
		}
		catch (final IOException ioException)
		{
			throw new IllegalStateException("Failed to reconstruct the secret from its shares",
				ioException);
		}
	}

	/**
	 * An immutable Shamir secret share, pairing the share's 1-based index with its value bytes.
	 * Both are required to reconstruct the original secret with {@link #combine(List)}.
	 */
	public static final class Share
	{

		private final int index;
		private final byte[] value;

		/**
		 * Instantiates a new {@link Share}.
		 *
		 * @param index
		 *            the 1-based share index
		 * @param value
		 *            the share value bytes
		 */
		public Share(final int index, final byte[] value)
		{
			this.index = index;
			this.value = Arrays.clone(Objects.requireNonNull(value));
		}

		/**
		 * Gets the 1-based share index.
		 *
		 * @return the 1-based share index
		 */
		public int getIndex()
		{
			return index;
		}

		/**
		 * Gets the share value bytes.
		 *
		 * @return a defensive copy of the share value bytes
		 */
		public byte[] getValue()
		{
			return Arrays.clone(value);
		}

	}

}
